permissions:
  contents: write

name: Release

on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Build
        run: |
          mvn install -pl :keycloak-crypto-fips1402,:keycloak-rest-admin-ui-ext,:keycloak-admin-cli -am -DskipTests &&
          mvn install -pl :keycloak-client-cli-dist -am -DskipTests &&
          mvn install -pl :integration-arquillian-testsuite-providers,:integration-arquillian-testsuite-providers-deployment,org.keycloak:keycloak-custom-db -am -DskipTests -Dexec.skip=true && 
          mvn install -f quarkus/pom.xml -DskipTests -DskipTestsuite &&
          cd quarkus/dist && 
          mvn clean install -DskipTests

      
      # Erst das Release erstellen
      - name: Create Initial Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            quarkus/dist/target/keycloak-*.zip
            quarkus/dist/target/keycloak-*.tar.gz
            custom-db-module-relations/target/*.jar
      
      # Dann das Docker Image bauen mit dem Link zum Release
      - name: Build Docker image
        run: |
          cd quarkus/container
          docker build --build-arg KEYCLOAK_DIST=https://github.com/MikloManuel/heartfull-mind-keycloak-human-resources/releases/download/${{ github.ref_name }}/keycloak-999.0.0-SNAPSHOT.tar.gz -t heartfullmind/keycloak:${{ github.ref_name }} .
      
      - name: Save Docker image
        run: |
          docker save heartfullmind/keycloak:${{ github.ref_name }} | gzip > quarkus/dist/target/heartfullmind-keycloak-docker-image.tar.gz
      
      # Update das Release mit dem Docker Image
      - name: Update Release with Docker Image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: quarkus/dist/target/heartfullmind-keycloak-docker-image.tar.gz
          update_release: true
