permissions:
  contents: write

name: Release
on:
  push:
    tags:
      - 'v*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        run: |
          mvn install -pl :keycloak-crypto-fips1402,:keycloak-rest-admin-ui-ext,:keycloak-client-cli-dist -am -DskipTests &&
          mvn install -pl :integration-arquillian-testsuite-providers,:integration-arquillian-testsuite-providers-deployment,org.keycloak:keycloak-custom-db -am -DskipTests -Dexec.skip=true && 
          mvn install -f quarkus/pom.xml -DskipTests &&
          cd quarkus/dist && 
          mvn clean install -DskipTests
      - name: List files
        run: ls -la quarkus/dist/target/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            quarkus/dist/target/keycloak-*.zip
            quarkus/dist/target/keycloak-*.tar.gz
            custom-db-module-relations/target/*.jar